travis:
  secure:
    BINSTAR_TOKEN: XhZrqhXLMoEOVh8STnjzXRiFcgoeOxdY2TmIjQuikZBxQmYgFZO47834+iufkYHVNWwwSmdS09K0QuUaHqruhg4C31KAL0gW/8E9hMOhQySfRfuMCCaHWs+sbRMeE7r77uvHZF+KcaCo5pmBgszYt7ITLomwq0VukuH1yEn3G4nn3H3zbFeDXILcC+m/QWU8GmucoWzHzshdiZON2B8M7WU+GUubhIj0Qb7Mg+DoUskrN7M5YEnW0T86v08BjQ18af60NB771AtO6j4JEiuNYJC4dRwyLpPCynMpqy9G1fvyIKJ+9jxvRUaZOgRQaANGkxAKUUH9rOg2l8tzgNXEMCQy7n7DTUKFP6O+iZBGNSI1oTv6t/a0LOhKjtwyd2ItQRCCcGbvLRPSGVO8qJKBq/TduOybOB6h4mhp/V+CG6PNrevUJusIPAFqYdJwIVGX/rL/6W8PBMehnzAgRhV8w5/Zp43Mr2R0SHDyv2s2GDZwVsuNVNCKcQOIzQ5tk5PzavxYoTV1C0yhaIGVu72cYI6V94kLtdEJpfPdjX3LfkDWcjSG5fQQSnFvm1vMXDTssaamy4N34IJoGU3Zy+Hz140Nxdg2DUlU49gIzG44u4qzMSO3ldOJ2kgPA4dNdKVCXjdaJs/Ixt57QhNXk4E+qLZ0RmAxtYUcnLD0qwDYaV8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
